name: CI

on:
  push:
    branches: [ "demo" ]
  pull_request:
    branches: [ "demo" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: pip3 install databricks-cli

      - name: Configure Databricks CLI
        run: |
          mkdir -p ~/.databricks
          cat <<EOF > ~/.databricks/config
          [DEFAULT]
          host = https://dbc-3d485d2b-385d.cloud.databricks.com
          token = ${{ secrets.DATABRICKS_TOKEN }}
          EOF

      - name: Verify Databricks CLI login
        run: databricks workspace list /Users/kennnethcarlson@gmail.com
