name: Deploy to Databricks

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run notebook on serverless compute
        uses: databricks/run-notebook@v0.0.3
        with:
          databricks-host: ${{ secrets.DATABRICKS_HOST }}
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          notebook-path: "https://dbc-3d485d2b-385d.cloud.databricks.com/editor/notebooks/1236242030962204?o=1299670065630970
/Workspace/Users/kennnethcarlson@gmail.com/sample"
          new-cluster-json: |
            {
              "spark_version": "13.3.x-scala2.12",
              "runtime_engine": "PHOTON",
              "num_workers":1
            }
